# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CS_design.ui'
#
# Created: Wed Sep 19 17:06:11 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_CornerStitch_Dialog(object):
    def setupUi(self, CornerStitch_Dialog):
        CornerStitch_Dialog.setObjectName("CornerStitch_Dialog")
        CornerStitch_Dialog.resize(1103, 747)
        self.gridLayout = QtGui.QGridLayout(CornerStitch_Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.grbox_view = QtGui.QGroupBox(CornerStitch_Dialog)
        self.grbox_view.setMinimumSize(QtCore.QSize(600, 600))
        self.grbox_view.setMaximumSize(QtCore.QSize(600, 600))
        self.grbox_view.setObjectName("grbox_view")
        self.grview_layout_sols = QtGui.QGraphicsView(self.grbox_view)
        self.grview_layout_sols.setGeometry(QtCore.QRect(10, 23, 600, 600))
        self.grview_layout_sols.setMinimumSize(QtCore.QSize(600, 600))
        self.grview_layout_sols.setMaximumSize(QtCore.QSize(600, 600))
        self.grview_layout_sols.setObjectName("grview_layout_sols")
        self.gridLayout.addWidget(self.grbox_view, 0, 0, 7, 1)
        self.grbox_modes = QtGui.QGroupBox(CornerStitch_Dialog)
        self.grbox_modes.setMaximumSize(QtCore.QSize(16777215, 50))
        self.grbox_modes.setObjectName("grbox_modes")
        self.cmb_modes = QtGui.QComboBox(self.grbox_modes)
        self.cmb_modes.setGeometry(QtCore.QRect(110, 30, 261, 20))
        self.cmb_modes.setObjectName("cmb_modes")
        self.cmb_modes.addItem("")
        self.cmb_modes.addItem("")
        self.cmb_modes.addItem("")
        self.cmb_modes.addItem("")
        self.gridLayout.addWidget(self.grbox_modes, 0, 1, 1, 2)
        self.groupBox = QtGui.QGroupBox(CornerStitch_Dialog)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox.setObjectName("groupBox")
        self.txt_num_layouts = QtGui.QLineEdit(self.groupBox)
        self.txt_num_layouts.setGeometry(QtCore.QRect(130, 30, 171, 20))
        self.txt_num_layouts.setObjectName("txt_num_layouts")
        self.lbl_num_layouts = QtGui.QLabel(self.groupBox)
        self.lbl_num_layouts.setGeometry(QtCore.QRect(20, 30, 81, 20))
        self.lbl_num_layouts.setMaximumSize(QtCore.QSize(100, 100))
        self.lbl_num_layouts.setObjectName("lbl_num_layouts")
        self.lbl_sols = QtGui.QLabel(self.groupBox)
        self.lbl_sols.setGeometry(QtCore.QRect(20, 70, 83, 20))
        self.lbl_sols.setMinimumSize(QtCore.QSize(0, 20))
        self.lbl_sols.setMaximumSize(QtCore.QSize(100, 100))
        self.lbl_sols.setObjectName("lbl_sols")
        self.cmb_sols = QtGui.QComboBox(self.groupBox)
        self.cmb_sols.setGeometry(QtCore.QRect(130, 70, 161, 20))
        self.cmb_sols.setObjectName("cmb_sols")
        self.gridLayout.addWidget(self.groupBox, 2, 1, 1, 2)
        self.grbox_flsize = QtGui.QGroupBox(CornerStitch_Dialog)
        self.grbox_flsize.setMaximumSize(QtCore.QSize(16777215, 100))
        self.grbox_flsize.setObjectName("grbox_flsize")
        self.gridLayout_2 = QtGui.QGridLayout(self.grbox_flsize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txt_width = QtGui.QLineEdit(self.grbox_flsize)
        self.txt_width.setObjectName("txt_width")
        self.gridLayout_2.addWidget(self.txt_width, 0, 1, 1, 1)
        self.lbl_height_2 = QtGui.QLabel(self.grbox_flsize)
        self.lbl_height_2.setObjectName("lbl_height_2")
        self.gridLayout_2.addWidget(self.lbl_height_2, 0, 2, 1, 1)
        self.lbl_width = QtGui.QLabel(self.grbox_flsize)
        self.lbl_width.setMinimumSize(QtCore.QSize(0, 20))
        self.lbl_width.setMaximumSize(QtCore.QSize(100, 100))
        self.lbl_width.setObjectName("lbl_width")
        self.gridLayout_2.addWidget(self.lbl_width, 0, 0, 1, 1)
        self.txt_height = QtGui.QLineEdit(self.grbox_flsize)
        self.txt_height.setObjectName("txt_height")
        self.gridLayout_2.addWidget(self.txt_height, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.grbox_flsize, 1, 1, 1, 2)
        self.btn_fixed_locs = QtGui.QPushButton(CornerStitch_Dialog)
        self.btn_fixed_locs.setObjectName("btn_fixed_locs")
        self.gridLayout.addWidget(self.btn_fixed_locs, 3, 1, 1, 1)
        self.btn_constraints = QtGui.QPushButton(CornerStitch_Dialog)
        self.btn_constraints.setObjectName("btn_constraints")
        self.gridLayout.addWidget(self.btn_constraints, 3, 2, 1, 1)
        self.btn_eval_layout = QtGui.QPushButton(CornerStitch_Dialog)
        self.btn_eval_layout.setObjectName("btn_eval_layout")
        self.gridLayout.addWidget(self.btn_eval_layout, 4, 1, 1, 1)
        self.btn_gen_layouts = QtGui.QPushButton(CornerStitch_Dialog)
        self.btn_gen_layouts.setMinimumSize(QtCore.QSize(200, 23))
        self.btn_gen_layouts.setMaximumSize(QtCore.QSize(16777215, 23))
        self.btn_gen_layouts.setObjectName("btn_gen_layouts")
        self.gridLayout.addWidget(self.btn_gen_layouts, 4, 2, 1, 1)
        self.lbl_step = QtGui.QLabel(CornerStitch_Dialog)
        self.lbl_step.setObjectName("lbl_step")
        self.gridLayout.addWidget(self.lbl_step, 5, 1, 1, 2)

        self.retranslateUi(CornerStitch_Dialog)
        QtCore.QMetaObject.connectSlotsByName(CornerStitch_Dialog)

    def retranslateUi(self, CornerStitch_Dialog):
        CornerStitch_Dialog.setWindowTitle(QtGui.QApplication.translate("CornerStitch_Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.grbox_view.setTitle(QtGui.QApplication.translate("CornerStitch_Dialog", "Layout Window", None, QtGui.QApplication.UnicodeUTF8))
        self.grbox_modes.setTitle(QtGui.QApplication.translate("CornerStitch_Dialog", "Modes", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_modes.setItemText(0, QtGui.QApplication.translate("CornerStitch_Dialog", "Mode 0", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_modes.setItemText(1, QtGui.QApplication.translate("CornerStitch_Dialog", "Mode 1", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_modes.setItemText(2, QtGui.QApplication.translate("CornerStitch_Dialog", "Mode 2", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_modes.setItemText(3, QtGui.QApplication.translate("CornerStitch_Dialog", "Mode 3", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("CornerStitch_Dialog", "Layouts Solutions", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_num_layouts.setText(QtGui.QApplication.translate("CornerStitch_Dialog", "Num of layouts", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_sols.setText(QtGui.QApplication.translate("CornerStitch_Dialog", "Layout Solutions:", None, QtGui.QApplication.UnicodeUTF8))
        self.grbox_flsize.setTitle(QtGui.QApplication.translate("CornerStitch_Dialog", "Florrplan size", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_height_2.setText(QtGui.QApplication.translate("CornerStitch_Dialog", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_width.setText(QtGui.QApplication.translate("CornerStitch_Dialog", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_fixed_locs.setText(QtGui.QApplication.translate("CornerStitch_Dialog", "Fixed Locations", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_constraints.setText(QtGui.QApplication.translate("CornerStitch_Dialog", "Assign Constraints", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_eval_layout.setText(QtGui.QApplication.translate("CornerStitch_Dialog", "Evaluate", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_gen_layouts.setText(QtGui.QApplication.translate("CornerStitch_Dialog", "Generate Layouts", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_step.setText(QtGui.QApplication.translate("CornerStitch_Dialog", "Step to run ....", None, QtGui.QApplication.UnicodeUTF8))

