# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CS_design_up.ui'
#
# Created: Tue Apr 16 19:20:49 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_CornerStitch_Dialog(object):
    def setupUi(self, CornerStitch_Dialog):
        CornerStitch_Dialog.setObjectName("CornerStitch_Dialog")
        CornerStitch_Dialog.resize(1118, 733)
        self.gridLayout_7 = QtGui.QGridLayout(CornerStitch_Dialog)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.grbox_view = QtGui.QGroupBox(CornerStitch_Dialog)
        self.grbox_view.setMinimumSize(QtCore.QSize(600, 600))
        self.grbox_view.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.grbox_view.setObjectName("grbox_view")
        self.gridLayout_9 = QtGui.QGridLayout(self.grbox_view)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_4 = QtGui.QGroupBox(self.grbox_view)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.grview_layout_sols = QtGui.QGraphicsView(self.groupBox_4)
        self.grview_layout_sols.setObjectName("grview_layout_sols")
        self.gridLayout_6.addWidget(self.grview_layout_sols, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.grbox_view)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.grview_init_layout = QtGui.QGraphicsView(self.groupBox_5)
        self.grview_init_layout.setObjectName("grview_init_layout")
        self.gridLayout_8.addWidget(self.grview_init_layout, 0, 0, 1, 1)
        self.Node_ID = QtGui.QLabel(self.groupBox_5)
        self.Node_ID.setObjectName("Node_ID")
        self.gridLayout_8.addWidget(self.Node_ID, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.grbox_view, 0, 0, 3, 1)
        self.grbox_modes = QtGui.QGroupBox(CornerStitch_Dialog)
        self.grbox_modes.setMaximumSize(QtCore.QSize(16777215, 50))
        self.grbox_modes.setObjectName("grbox_modes")
        self.gridLayout_5 = QtGui.QGridLayout(self.grbox_modes)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cmb_modes = QtGui.QComboBox(self.grbox_modes)
        self.cmb_modes.setObjectName("cmb_modes")
        self.cmb_modes.addItem("")
        self.cmb_modes.addItem("")
        self.cmb_modes.addItem("")
        self.cmb_modes.addItem("")
        self.gridLayout_5.addWidget(self.cmb_modes, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.grbox_modes, 0, 1, 1, 1)
        self.grbox_flsize = QtGui.QGroupBox(CornerStitch_Dialog)
        self.grbox_flsize.setMaximumSize(QtCore.QSize(16777215, 100))
        self.grbox_flsize.setObjectName("grbox_flsize")
        self.gridLayout_2 = QtGui.QGridLayout(self.grbox_flsize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_width = QtGui.QLabel(self.grbox_flsize)
        self.lbl_width.setMinimumSize(QtCore.QSize(0, 20))
        self.lbl_width.setMaximumSize(QtCore.QSize(100, 100))
        self.lbl_width.setObjectName("lbl_width")
        self.gridLayout_2.addWidget(self.lbl_width, 0, 0, 1, 1)
        self.txt_width = QtGui.QLineEdit(self.grbox_flsize)
        self.txt_width.setObjectName("txt_width")
        self.gridLayout_2.addWidget(self.txt_width, 0, 1, 1, 1)
        self.lbl_height_2 = QtGui.QLabel(self.grbox_flsize)
        self.lbl_height_2.setObjectName("lbl_height_2")
        self.gridLayout_2.addWidget(self.lbl_height_2, 0, 2, 1, 1)
        self.txt_height = QtGui.QLineEdit(self.grbox_flsize)
        self.txt_height.setObjectName("txt_height")
        self.gridLayout_2.addWidget(self.txt_height, 0, 3, 1, 1)
        self.gridLayout_7.addWidget(self.grbox_flsize, 0, 2, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(CornerStitch_Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_sel_sol = QtGui.QPushButton(self.groupBox_2)
        self.btn_sel_sol.setObjectName("btn_sel_sol")
        self.gridLayout_4.addWidget(self.btn_sel_sol, 1, 0, 1, 1)
        self.btn_save_all = QtGui.QPushButton(self.groupBox_2)
        self.btn_save_all.setObjectName("btn_save_all")
        self.gridLayout_4.addWidget(self.btn_save_all, 1, 1, 1, 1)
        self.grview_sols_browser = QtGui.QGraphicsView(self.groupBox_2)
        self.grview_sols_browser.setObjectName("grview_sols_browser")
        self.gridLayout_4.addWidget(self.grview_sols_browser, 0, 0, 1, 2)
        self.gridLayout_7.addWidget(self.groupBox_2, 2, 1, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(CornerStitch_Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_fixed_locs = QtGui.QPushButton(self.groupBox_3)
        self.btn_fixed_locs.setObjectName("btn_fixed_locs")
        self.gridLayout.addWidget(self.btn_fixed_locs, 0, 0, 1, 1)
        self.btn_constraints = QtGui.QPushButton(self.groupBox_3)
        self.btn_constraints.setObjectName("btn_constraints")
        self.gridLayout.addWidget(self.btn_constraints, 0, 1, 1, 1)
        self.btn_eval_setup = QtGui.QPushButton(self.groupBox_3)
        self.btn_eval_setup.setObjectName("btn_eval_setup")
        self.gridLayout.addWidget(self.btn_eval_setup, 1, 0, 1, 1)
        self.btn_gen_layouts = QtGui.QPushButton(self.groupBox_3)
        self.btn_gen_layouts.setMinimumSize(QtCore.QSize(100, 23))
        self.btn_gen_layouts.setMaximumSize(QtCore.QSize(16777215, 23))
        self.btn_gen_layouts.setObjectName("btn_gen_layouts")
        self.gridLayout.addWidget(self.btn_gen_layouts, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 1, 1, 1, 2)

        self.retranslateUi(CornerStitch_Dialog)
        QtCore.QMetaObject.connectSlotsByName(CornerStitch_Dialog)

    def retranslateUi(self, CornerStitch_Dialog):
        CornerStitch_Dialog.setWindowTitle(QtGui.QApplication.translate("CornerStitch_Dialog", "PowerSynth (v1.2) Layout Engine ", None, QtGui.QApplication.UnicodeUTF8))
        self.grbox_view.setTitle(QtGui.QApplication.translate("CornerStitch_Dialog", "Layout Visualization", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("CornerStitch_Dialog", "Generated Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("CornerStitch_Dialog", "Input (initial) Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.Node_ID.setText(QtGui.QApplication.translate("CornerStitch_Dialog", "Node ID : ", None, QtGui.QApplication.UnicodeUTF8))
        self.grbox_modes.setTitle(QtGui.QApplication.translate("CornerStitch_Dialog", "Modes", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_modes.setItemText(0, QtGui.QApplication.translate("CornerStitch_Dialog", "Minimum Size Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_modes.setItemText(1, QtGui.QApplication.translate("CornerStitch_Dialog", "Variable Size Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_modes.setItemText(2, QtGui.QApplication.translate("CornerStitch_Dialog", "Fixed Size Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_modes.setItemText(3, QtGui.QApplication.translate("CornerStitch_Dialog", "Fixed Size with Fixed Loactions", None, QtGui.QApplication.UnicodeUTF8))
        self.grbox_flsize.setTitle(QtGui.QApplication.translate("CornerStitch_Dialog", "Floorplan size", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_width.setText(QtGui.QApplication.translate("CornerStitch_Dialog", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_height_2.setText(QtGui.QApplication.translate("CornerStitch_Dialog", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("CornerStitch_Dialog", "Layout Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_sel_sol.setText(QtGui.QApplication.translate("CornerStitch_Dialog", "Save Selected Solutions", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_all.setText(QtGui.QApplication.translate("CornerStitch_Dialog", "Save All Solutions", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("CornerStitch_Dialog", "Control Buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_fixed_locs.setText(QtGui.QApplication.translate("CornerStitch_Dialog", "Fixed Locations", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_constraints.setText(QtGui.QApplication.translate("CornerStitch_Dialog", "Assign Constraints", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_eval_setup.setText(QtGui.QApplication.translate("CornerStitch_Dialog", "Optimization Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_gen_layouts.setText(QtGui.QApplication.translate("CornerStitch_Dialog", "Generate Layouts", None, QtGui.QApplication.UnicodeUTF8))

