# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'device_setup_dialog.ui'
#
# Created: Tue Jun 05 15:48:54 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_setup_device(object):
    def setupUi(self, setup_device):
        setup_device.setObjectName("setup_device")
        setup_device.resize(257, 498)
        self.gridLayout = QtGui.QGridLayout(setup_device)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtGui.QFrame(setup_device)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_dev_attach = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lbl_dev_attach.setFont(font)
        self.lbl_dev_attach.setObjectName("lbl_dev_attach")
        self.gridLayout_2.addWidget(self.lbl_dev_attach, 0, 0, 1, 3)
        self.lst_devices_att = QtGui.QListView(self.frame)
        self.lst_devices_att.setEnabled(False)
        self.lst_devices_att.setMaximumSize(QtCore.QSize(16777215, 1000))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lst_devices_att.setPalette(palette)
        self.lst_devices_att.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lst_devices_att.setObjectName("lst_devices_att")
        self.gridLayout_2.addWidget(self.lst_devices_att, 1, 0, 1, 4)
        self.label_46 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.gridLayout_2.addWidget(self.label_46, 2, 0, 1, 1)
        self.txt_device_heat_flow = QtGui.QLineEdit(self.frame)
        self.txt_device_heat_flow.setEnabled(False)
        self.txt_device_heat_flow.setMaximumSize(QtCore.QSize(50, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.txt_device_heat_flow.setPalette(palette)
        self.txt_device_heat_flow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_device_heat_flow.setObjectName("txt_device_heat_flow")
        self.gridLayout_2.addWidget(self.txt_device_heat_flow, 2, 1, 1, 2)
        self.label_47 = QtGui.QLabel(self.frame)
        self.label_47.setObjectName("label_47")
        self.gridLayout_2.addWidget(self.label_47, 2, 3, 1, 1)
        self.label_20 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 3, 0, 1, 1)
        self.txt_devAttchThickness = QtGui.QLineEdit(self.frame)
        self.txt_devAttchThickness.setEnabled(False)
        self.txt_devAttchThickness.setMaximumSize(QtCore.QSize(50, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.txt_devAttchThickness.setPalette(palette)
        self.txt_devAttchThickness.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_devAttchThickness.setObjectName("txt_devAttchThickness")
        self.gridLayout_2.addWidget(self.txt_devAttchThickness, 3, 1, 1, 2)
        self.label_21 = QtGui.QLabel(self.frame)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 3, 3, 1, 1)
        self.btn_update_dev_setup = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btn_update_dev_setup.setFont(font)
        self.btn_update_dev_setup.setObjectName("btn_update_dev_setup")
        self.gridLayout_2.addWidget(self.btn_update_dev_setup, 4, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(82, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 2, 1, 2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.label_46.setBuddy(self.txt_device_heat_flow)
        self.label_20.setBuddy(self.txt_devAttchThickness)

        self.retranslateUi(setup_device)
        QtCore.QMetaObject.connectSlotsByName(setup_device)

    def retranslateUi(self, setup_device):
        setup_device.setWindowTitle(QtGui.QApplication.translate("setup_device", "Device Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_dev_attach.setText(QtGui.QApplication.translate("setup_device", "Select a Device Attach:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("setup_device", "Device Heat Flow:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("setup_device", "W", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("setup_device", "Attach Thickness:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("setup_device", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_update_dev_setup.setText(QtGui.QApplication.translate("setup_device", "Done", None, QtGui.QApplication.UnicodeUTF8))

