# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ET_evaluate_ui.ui'
#
# Created: Thu Sep 27 14:21:24 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ET_Evaluation_Dialog(object):
    def setupUi(self, ET_Evaluation_Dialog):
        ET_Evaluation_Dialog.setObjectName("ET_Evaluation_Dialog")
        ET_Evaluation_Dialog.resize(874, 571)
        self.gridLayout_5 = QtGui.QGridLayout(ET_Evaluation_Dialog)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtGui.QGroupBox(ET_Evaluation_Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tbl_perf_list = QtGui.QTableWidget(self.groupBox)
        self.tbl_perf_list.setObjectName("tbl_perf_list")
        self.tbl_perf_list.setColumnCount(3)
        self.tbl_perf_list.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbl_perf_list.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_perf_list.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_perf_list.setHorizontalHeaderItem(2, item)
        self.gridLayout_4.addWidget(self.tbl_perf_list, 0, 0, 1, 3)
        self.btn_done = QtGui.QPushButton(self.groupBox)
        self.btn_done.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_done.setObjectName("btn_done")
        self.gridLayout_4.addWidget(self.btn_done, 1, 2, 1, 1)
        self.btn_remove = QtGui.QPushButton(self.groupBox)
        self.btn_remove.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_remove.setObjectName("btn_remove")
        self.gridLayout_4.addWidget(self.btn_remove, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(ET_Evaluation_Dialog)
        self.groupBox_2.setMinimumSize(QtCore.QSize(500, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.txt_perfname = QtGui.QLineEdit(self.groupBox_2)
        self.txt_perfname.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txt_perfname.setObjectName("txt_perfname")
        self.gridLayout.addWidget(self.txt_perfname, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.Tab_model_select = QtGui.QTabWidget(self.groupBox_2)
        self.Tab_model_select.setEnabled(True)
        self.Tab_model_select.setMinimumSize(QtCore.QSize(450, 0))
        self.Tab_model_select.setMaximumSize(QtCore.QSize(450, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.Tab_model_select.setFont(font)
        self.Tab_model_select.setObjectName("Tab_model_select")
        self.Thermal = QtGui.QWidget()
        self.Thermal.setObjectName("Thermal")
        self.gridLayout_2 = QtGui.QGridLayout(self.Thermal)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cmb_thermal_type = QtGui.QComboBox(self.Thermal)
        self.cmb_thermal_type.setObjectName("cmb_thermal_type")
        self.cmb_thermal_type.addItem("")
        self.cmb_thermal_type.addItem("")
        self.cmb_thermal_type.addItem("")
        self.gridLayout_2.addWidget(self.cmb_thermal_type, 0, 2, 1, 1)
        self.tbl_thermal_data = QtGui.QTableWidget(self.Thermal)
        self.tbl_thermal_data.setMinimumSize(QtCore.QSize(300, 0))
        self.tbl_thermal_data.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tbl_thermal_data.setObjectName("tbl_thermal_data")
        self.tbl_thermal_data.setColumnCount(3)
        self.tbl_thermal_data.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbl_thermal_data.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_thermal_data.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_thermal_data.setHorizontalHeaderItem(2, item)
        self.gridLayout_2.addWidget(self.tbl_thermal_data, 1, 0, 1, 3)
        self.lbl_thermal_mdl = QtGui.QLabel(self.Thermal)
        self.lbl_thermal_mdl.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbl_thermal_mdl.setObjectName("lbl_thermal_mdl")
        self.gridLayout_2.addWidget(self.lbl_thermal_mdl, 0, 0, 1, 1)
        self.btn_thermal_perf = QtGui.QPushButton(self.Thermal)
        self.btn_thermal_perf.setObjectName("btn_thermal_perf")
        self.gridLayout_2.addWidget(self.btn_thermal_perf, 2, 0, 1, 3)
        self.cmb_thermal_mdl = QtGui.QComboBox(self.Thermal)
        self.cmb_thermal_mdl.setObjectName("cmb_thermal_mdl")
        self.cmb_thermal_mdl.addItem("")
        self.cmb_thermal_mdl.addItem("")
        self.gridLayout_2.addWidget(self.cmb_thermal_mdl, 0, 1, 1, 1)
        self.Tab_model_select.addTab(self.Thermal, "")
        self.Electrical = QtGui.QWidget()
        self.Electrical.setObjectName("electrical_mdl")
        self.gridLayout_3 = QtGui.QGridLayout(self.Electrical)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_select_mdl = QtGui.QPushButton(self.Electrical)
        self.btn_select_mdl.setObjectName("btn_select_mdl")
        self.gridLayout_3.addWidget(self.btn_select_mdl, 1, 1, 1, 1)
        self.cmb_src_select = QtGui.QComboBox(self.Electrical)
        self.cmb_src_select.setMinimumSize(QtCore.QSize(100, 0))
        self.cmb_src_select.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cmb_src_select.setObjectName("cmb_src_select")
        self.gridLayout_3.addWidget(self.cmb_src_select, 5, 1, 1, 1)
        self.lbl_electrical_mdl = QtGui.QLabel(self.Electrical)
        self.lbl_electrical_mdl.setObjectName("lbl_electrical_mdl")
        self.gridLayout_3.addWidget(self.lbl_electrical_mdl, 0, 0, 1, 1)
        self.cmb_electrical_mdl = QtGui.QComboBox(self.Electrical)
        self.cmb_electrical_mdl.setMinimumSize(QtCore.QSize(200, 0))
        self.cmb_electrical_mdl.setObjectName("cmb_electrical_mdl")
        self.cmb_electrical_mdl.addItem("")
        self.cmb_electrical_mdl.addItem("")
        self.cmb_electrical_mdl.addItem("")
        self.gridLayout_3.addWidget(self.cmb_electrical_mdl, 0, 1, 1, 2)
        self.cmb_electrical_type = QtGui.QComboBox(self.Electrical)
        self.cmb_electrical_type.setObjectName("cmb_electrical_type")
        self.cmb_electrical_type.addItem("")
        self.cmb_electrical_type.addItem("")
        self.cmb_electrical_type.addItem("")
        self.gridLayout_3.addWidget(self.cmb_electrical_type, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.Electrical)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 5, 0, 1, 1)
        self.btn_dv_states = QtGui.QPushButton(self.Electrical)
        self.btn_dv_states.setObjectName("btn_dv_states")
        self.gridLayout_3.addWidget(self.btn_dv_states, 6, 0, 1, 2)
        self.cmb_sink_select = QtGui.QComboBox(self.Electrical)
        self.cmb_sink_select.setMinimumSize(QtCore.QSize(100, 0))
        self.cmb_sink_select.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cmb_sink_select.setObjectName("cmb_sink_select")
        self.gridLayout_3.addWidget(self.cmb_sink_select, 5, 4, 1, 1)
        self.btn_add_elec_perf = QtGui.QPushButton(self.Electrical)
        self.btn_add_elec_perf.setObjectName("btn_add_elec_perf")
        self.gridLayout_3.addWidget(self.btn_add_elec_perf, 6, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.Electrical)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 5, 2, 1, 1)
        self.Tab_model_select.addTab(self.Electrical, "")
        self.gridLayout.addWidget(self.Tab_model_select, 1, 0, 1, 4)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 0, 1, 1)

        self.retranslateUi(ET_Evaluation_Dialog)
        self.Tab_model_select.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ET_Evaluation_Dialog)

    def retranslateUi(self, ET_Evaluation_Dialog):
        ET_Evaluation_Dialog.setWindowTitle(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Layout Evaluation", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Design Performance List", None, QtGui.QApplication.UnicodeUTF8))
        self.tbl_perf_list.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tbl_perf_list.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Measure Type", None, QtGui.QApplication.UnicodeUTF8))
        self.tbl_perf_list.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Evaluation Type", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_done.setText(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_remove.setText(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Performance Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Performance Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_thermal_type.setItemText(0, QtGui.QApplication.translate("ET_Evaluation_Dialog", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_thermal_type.setItemText(1, QtGui.QApplication.translate("ET_Evaluation_Dialog", "Average", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_thermal_type.setItemText(2, QtGui.QApplication.translate("ET_Evaluation_Dialog", "Std Deviation", None, QtGui.QApplication.UnicodeUTF8))
        self.tbl_thermal_data.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Device Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tbl_thermal_data.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Power Dissipation", None, QtGui.QApplication.UnicodeUTF8))
        self.tbl_thermal_data.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_thermal_mdl.setText(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Model:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_thermal_perf.setText(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Add Performance >>>", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_thermal_mdl.setItemText(0, QtGui.QApplication.translate("ET_Evaluation_Dialog", "Fast Approximation with FEM", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_thermal_mdl.setItemText(1, QtGui.QApplication.translate("ET_Evaluation_Dialog", "analytical Rectangular Flux", None, QtGui.QApplication.UnicodeUTF8))
        self.Tab_model_select.setTabText(self.Tab_model_select.indexOf(self.Thermal), QtGui.QApplication.translate("ET_Evaluation_Dialog", "Thermal", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_select_mdl.setText(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Select Model", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_electrical_mdl.setText(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Model:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_electrical_mdl.setItemText(0, QtGui.QApplication.translate("ET_Evaluation_Dialog", "Response Surface Model", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_electrical_mdl.setItemText(1, QtGui.QApplication.translate("ET_Evaluation_Dialog", "3D Hierarchical PEEC", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_electrical_mdl.setItemText(2, QtGui.QApplication.translate("ET_Evaluation_Dialog", "Microstrip Equations", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_electrical_type.setItemText(0, QtGui.QApplication.translate("ET_Evaluation_Dialog", "Inductance", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_electrical_type.setItemText(1, QtGui.QApplication.translate("ET_Evaluation_Dialog", "Resistance", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_electrical_type.setItemText(2, QtGui.QApplication.translate("ET_Evaluation_Dialog", "Capacitance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_dv_states.setText(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Setup Device States", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add_elec_perf.setText(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Add Performance >>>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ET_Evaluation_Dialog", "Sink", None, QtGui.QApplication.UnicodeUTF8))
        self.Tab_model_select.setTabText(self.Tab_model_select.indexOf(self.Electrical), QtGui.QApplication.translate("ET_Evaluation_Dialog", "electrical_mdl", None, QtGui.QApplication.UnicodeUTF8))

