# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fixed_loc.ui'
#
# Created: Wed Sep 26 14:01:19 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Fixed_location_Dialog(object):
    def setupUi(self, Fixed_location_Dialog):
        Fixed_location_Dialog.setObjectName("Fixed_location_Dialog")
        Fixed_location_Dialog.resize(473, 342)
        self.gridLayout_3 = QtGui.QGridLayout(Fixed_location_Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.grpbox_nodeinfo = QtGui.QGroupBox(Fixed_location_Dialog)
        self.grpbox_nodeinfo.setMinimumSize(QtCore.QSize(450, 0))
        self.grpbox_nodeinfo.setMaximumSize(QtCore.QSize(450, 16777215))
        self.grpbox_nodeinfo.setObjectName("grpbox_nodeinfo")
        self.gridLayout = QtGui.QGridLayout(self.grpbox_nodeinfo)
        self.gridLayout.setObjectName("gridLayout")
        self.cmb_nodes = QtGui.QComboBox(self.grpbox_nodeinfo)
        self.cmb_nodes.setMinimumSize(QtCore.QSize(100, 0))
        self.cmb_nodes.setObjectName("cmb_nodes")
        self.gridLayout.addWidget(self.cmb_nodes, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.grpbox_nodeinfo)
        self.label_2.setMinimumSize(QtCore.QSize(10, 0))
        self.label_2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.txt_inputy = QtGui.QLineEdit(self.grpbox_nodeinfo)
        self.txt_inputy.setMinimumSize(QtCore.QSize(100, 0))
        self.txt_inputy.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txt_inputy.setObjectName("txt_inputy")
        self.gridLayout.addWidget(self.txt_inputy, 0, 5, 1, 1)
        self.label = QtGui.QLabel(self.grpbox_nodeinfo)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.grpbox_nodeinfo)
        self.label_3.setMinimumSize(QtCore.QSize(10, 0))
        self.label_3.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.lbl_minxy = QtGui.QLabel(self.grpbox_nodeinfo)
        self.lbl_minxy.setObjectName("lbl_minxy")
        self.gridLayout.addWidget(self.lbl_minxy, 1, 0, 1, 5)
        self.btn_addnode = QtGui.QPushButton(self.grpbox_nodeinfo)
        self.btn_addnode.setObjectName("btn_addnode")
        self.gridLayout.addWidget(self.btn_addnode, 1, 5, 1, 1)
        self.txt_inputx = QtGui.QLineEdit(self.grpbox_nodeinfo)
        self.txt_inputx.setMinimumSize(QtCore.QSize(100, 0))
        self.txt_inputx.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txt_inputx.setObjectName("txt_inputx")
        self.gridLayout.addWidget(self.txt_inputx, 0, 3, 1, 1)
        self.gridLayout_3.addWidget(self.grpbox_nodeinfo, 0, 0, 1, 1)
        self.grpbox_Fixedloc = QtGui.QGroupBox(Fixed_location_Dialog)
        self.grpbox_Fixedloc.setMinimumSize(QtCore.QSize(450, 0))
        self.grpbox_Fixedloc.setMaximumSize(QtCore.QSize(450, 16777215))
        self.grpbox_Fixedloc.setObjectName("grpbox_Fixedloc")
        self.gridLayout_2 = QtGui.QGridLayout(self.grpbox_Fixedloc)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_rmvnode = QtGui.QPushButton(self.grpbox_Fixedloc)
        self.btn_rmvnode.setObjectName("btn_rmvnode")
        self.gridLayout_2.addWidget(self.btn_rmvnode, 1, 0, 1, 1)
        self.btn_save = QtGui.QPushButton(self.grpbox_Fixedloc)
        self.btn_save.setObjectName("btn_save")
        self.gridLayout_2.addWidget(self.btn_save, 1, 1, 1, 1)
        self.table_Fixedloc = QtGui.QTableWidget(self.grpbox_Fixedloc)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.table_Fixedloc.setFont(font)
        self.table_Fixedloc.setColumnCount(3)
        self.table_Fixedloc.setObjectName("table_Fixedloc")
        self.table_Fixedloc.setColumnCount(3)
        self.table_Fixedloc.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_Fixedloc.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_Fixedloc.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_Fixedloc.setHorizontalHeaderItem(2, item)
        self.table_Fixedloc.horizontalHeader().setDefaultSectionSize(140)
        self.gridLayout_2.addWidget(self.table_Fixedloc, 0, 0, 1, 2)
        self.gridLayout_3.addWidget(self.grpbox_Fixedloc, 1, 0, 1, 1)

        self.retranslateUi(Fixed_location_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Fixed_location_Dialog)

    def retranslateUi(self, Fixed_location_Dialog):
        Fixed_location_Dialog.setWindowTitle(QtGui.QApplication.translate("Fixed_location_Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.grpbox_nodeinfo.setTitle(QtGui.QApplication.translate("Fixed_location_Dialog", "Node Information", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Fixed_location_Dialog", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Fixed_location_Dialog", "Node ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Fixed_location_Dialog", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_minxy.setText(QtGui.QApplication.translate("Fixed_location_Dialog", "Node min locations X: ---- Y:----", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_addnode.setText(QtGui.QApplication.translate("Fixed_location_Dialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.grpbox_Fixedloc.setTitle(QtGui.QApplication.translate("Fixed_location_Dialog", "Fixed Locations Table", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_rmvnode.setText(QtGui.QApplication.translate("Fixed_location_Dialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save.setText(QtGui.QApplication.translate("Fixed_location_Dialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.table_Fixedloc.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Fixed_location_Dialog", "Node ID", None, QtGui.QApplication.UnicodeUTF8))
        self.table_Fixedloc.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Fixed_location_Dialog", "X Location", None, QtGui.QApplication.UnicodeUTF8))
        self.table_Fixedloc.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Fixed_location_Dialog", "Y Location", None, QtGui.QApplication.UnicodeUTF8))

