# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newProjectDialog.ui'
#
# Created: Tue Jun 12 10:27:45 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_newProjectDialog(object):
    def setupUi(self, newProjectDialog):
        newProjectDialog.setObjectName("newProjectDialog")
        newProjectDialog.resize(518, 517)
        self.gridLayout = QtGui.QGridLayout(newProjectDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(newProjectDialog)
        self.groupBox.setMinimumSize(QtCore.QSize(500, 499))
        self.groupBox.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_cancel = QtGui.QPushButton(self.groupBox)
        self.btn_cancel.setMaximumSize(QtCore.QSize(150, 34))
        self.btn_cancel.setObjectName("btn_cancel")
        self.gridLayout_2.addWidget(self.btn_cancel, 5, 3, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_advnetlist = QtGui.QGroupBox(self.groupBox)
        self.groupBox_advnetlist.setMaximumSize(QtCore.QSize(800, 100))
        self.groupBox_advnetlist.setObjectName("groupBox_advnetlist")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_advnetlist)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtGui.QLabel(self.groupBox_advnetlist)
        self.label_8.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.btn_net_import = QtGui.QToolButton(self.groupBox_advnetlist)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_net_import.sizePolicy().hasHeightForWidth())
        self.btn_net_import.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.btn_net_import.setFont(font)
        self.btn_net_import.setObjectName("btn_net_import")
        self.gridLayout_4.addWidget(self.btn_net_import, 0, 1, 1, 1)
        self.txt_symbnet_address_2 = QtGui.QLineEdit(self.groupBox_advnetlist)
        self.txt_symbnet_address_2.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txt_symbnet_address_2.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.txt_symbnet_address_2.setFont(font)
        self.txt_symbnet_address_2.setObjectName("txt_symbnet_address_2")
        self.gridLayout_4.addWidget(self.txt_symbnet_address_2, 0, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_advnetlist)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 0, 1, 4)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtGui.QLabel(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setMinimumSize(QtCore.QSize(75, 0))
        self.label_7.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.btn_symbnetfile = QtGui.QToolButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_symbnetfile.sizePolicy().hasHeightForWidth())
        self.btn_symbnetfile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.btn_symbnetfile.setFont(font)
        self.btn_symbnetfile.setObjectName("btn_symbnetfile")
        self.gridLayout_5.addWidget(self.btn_symbnetfile, 1, 3, 1, 1)
        self.txt_symbnet_address = QtGui.QLineEdit(self.groupBox)
        self.txt_symbnet_address.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txt_symbnet_address.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.txt_symbnet_address.setFont(font)
        self.txt_symbnet_address.setObjectName("txt_symbnet_address")
        self.gridLayout_5.addWidget(self.txt_symbnet_address, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 2, 0, 1, 4)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.txt_name = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.txt_name.setFont(font)
        self.txt_name.setObjectName("txt_name")
        self.gridLayout_7.addWidget(self.txt_name, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_7, 0, 0, 1, 4)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.txt_dir = QtGui.QLineEdit(self.groupBox)
        self.txt_dir.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txt_dir.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.txt_dir.setFont(font)
        self.txt_dir.setReadOnly(False)
        self.txt_dir.setObjectName("txt_dir")
        self.gridLayout_6.addWidget(self.txt_dir, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(80, 50))
        self.label_3.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 1, 1, 1)
        self.btn_openDirectory = QtGui.QToolButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_openDirectory.sizePolicy().hasHeightForWidth())
        self.btn_openDirectory.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.btn_openDirectory.setFont(font)
        self.btn_openDirectory.setObjectName("btn_openDirectory")
        self.gridLayout_6.addWidget(self.btn_openDirectory, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 1, 0, 1, 4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 1, 1, 1)
        self.btn_create = QtGui.QPushButton(self.groupBox)
        self.btn_create.setEnabled(True)
        self.btn_create.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_create.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_create.setDefault(True)
        self.btn_create.setObjectName("btn_create")
        self.gridLayout_2.addWidget(self.btn_create, 5, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(newProjectDialog)
        QtCore.QMetaObject.connectSlotsByName(newProjectDialog)

    def retranslateUi(self, newProjectDialog):
        newProjectDialog.setWindowTitle(QtGui.QApplication.translate("newProjectDialog", "New Project", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("newProjectDialog", "________Create a new project________", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancel.setText(QtGui.QApplication.translate("newProjectDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_advnetlist.setTitle(QtGui.QApplication.translate("newProjectDialog", "Import netlist file (optional):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("newProjectDialog", "Select file", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_net_import.setText(QtGui.QApplication.translate("newProjectDialog", "Open File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("newProjectDialog", "Select either a script (.psc or .txt) file.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("newProjectDialog", "Select file:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_symbnetfile.setText(QtGui.QApplication.translate("newProjectDialog", "Open File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("newProjectDialog", "Project Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("newProjectDialog", "Project Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_openDirectory.setText(QtGui.QApplication.translate("newProjectDialog", "Open Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_create.setText(QtGui.QApplication.translate("newProjectDialog", "Create Project", None, QtGui.QApplication.UnicodeUTF8))

