# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\jhmain\workspace\PowerCAD\src\powercad\project_builder\ui\newProjectDialog.ui'
#
# Created: Thu Jun 25 15:11:12 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_newProjectDialog(object):
    def setupUi(self, newProjectDialog):
        newProjectDialog.setObjectName("newProjectDialog")
        newProjectDialog.resize(514, 501)
        self.label = QtGui.QLabel(newProjectDialog)
        self.label.setGeometry(QtCore.QRect(210, 10, 111, 91))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_5 = QtGui.QLabel(newProjectDialog)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 411, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.groupBox = QtGui.QGroupBox(newProjectDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 100, 491, 351))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 471, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.btn_openDirectory = QtGui.QToolButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_openDirectory.sizePolicy().hasHeightForWidth())
        self.btn_openDirectory.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.btn_openDirectory.setFont(font)
        self.btn_openDirectory.setObjectName("btn_openDirectory")
        self.horizontalLayout_3.addWidget(self.btn_openDirectory)
        self.txt_dir = QtGui.QLineEdit(self.layoutWidget)
        self.txt_dir.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txt_dir.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.txt_dir.setFont(font)
        self.txt_dir.setReadOnly(False)
        self.txt_dir.setObjectName("txt_dir")
        self.horizontalLayout_3.addWidget(self.txt_dir)
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 471, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.txt_name = QtGui.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.txt_name.setFont(font)
        self.txt_name.setObjectName("txt_name")
        self.horizontalLayout_4.addWidget(self.txt_name)
        self.layoutWidget2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 150, 471, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.btn_symbnetfile = QtGui.QToolButton(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_symbnetfile.sizePolicy().hasHeightForWidth())
        self.btn_symbnetfile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.btn_symbnetfile.setFont(font)
        self.btn_symbnetfile.setObjectName("btn_symbnetfile")
        self.horizontalLayout_2.addWidget(self.btn_symbnetfile)
        self.txt_symbnet_address = QtGui.QLineEdit(self.layoutWidget2)
        self.txt_symbnet_address.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txt_symbnet_address.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.txt_symbnet_address.setFont(font)
        self.txt_symbnet_address.setObjectName("txt_symbnet_address")
        self.horizontalLayout_2.addWidget(self.txt_symbnet_address)
        self.groupBox_advnetlist = QtGui.QGroupBox(self.groupBox)
        self.groupBox_advnetlist.setGeometry(QtCore.QRect(10, 180, 471, 161))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_advnetlist.setFont(font)
        self.groupBox_advnetlist.setObjectName("groupBox_advnetlist")
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_advnetlist)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 70, 451, 22))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtGui.QLabel(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.txt_positive_source = QtGui.QLineEdit(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_positive_source.sizePolicy().hasHeightForWidth())
        self.txt_positive_source.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.txt_positive_source.setFont(font)
        self.txt_positive_source.setObjectName("txt_positive_source")
        self.horizontalLayout_7.addWidget(self.txt_positive_source)
        self.err_pos_src = QtGui.QLabel(self.layoutWidget3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.err_pos_src.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.err_pos_src.setFont(font)
        self.err_pos_src.setText("")
        self.err_pos_src.setObjectName("err_pos_src")
        self.horizontalLayout_7.addWidget(self.err_pos_src)
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_advnetlist)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 100, 451, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.txt_negative_source = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_negative_source.sizePolicy().hasHeightForWidth())
        self.txt_negative_source.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.txt_negative_source.setFont(font)
        self.txt_negative_source.setObjectName("txt_negative_source")
        self.horizontalLayout_8.addWidget(self.txt_negative_source)
        self.err_neg_src = QtGui.QLabel(self.layoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.err_neg_src.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.err_neg_src.setFont(font)
        self.err_neg_src.setText("")
        self.err_neg_src.setObjectName("err_neg_src")
        self.horizontalLayout_8.addWidget(self.err_neg_src)
        self.label_6 = QtGui.QLabel(self.groupBox_advnetlist)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 451, 41))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.layoutWidget_3 = QtGui.QWidget(self.groupBox_advnetlist)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 130, 451, 22))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtGui.QLabel(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.txt_output = QtGui.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_output.sizePolicy().hasHeightForWidth())
        self.txt_output.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.txt_output.setFont(font)
        self.txt_output.setObjectName("txt_output")
        self.horizontalLayout_9.addWidget(self.txt_output)
        self.err_output_node = QtGui.QLabel(self.layoutWidget_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.err_output_node.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.err_output_node.setFont(font)
        self.err_output_node.setText("")
        self.err_output_node.setObjectName("err_output_node")
        self.horizontalLayout_9.addWidget(self.err_output_node)
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 100, 461, 20))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.layoutWidget4 = QtGui.QWidget(self.groupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 120, 211, 22))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.dropdown_filetype = QtGui.QComboBox(self.layoutWidget4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.dropdown_filetype.setFont(font)
        self.dropdown_filetype.setObjectName("dropdown_filetype")
        self.dropdown_filetype.addItem("")
        self.dropdown_filetype.addItem("")
        self.dropdown_filetype.addItem("")
        self.dropdown_filetype.addItem("")
        self.horizontalLayout_5.addWidget(self.dropdown_filetype)
        self.layoutWidget5 = QtGui.QWidget(newProjectDialog)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 460, 491, 25))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(247, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_cancel = QtGui.QPushButton(self.layoutWidget5)
        self.btn_cancel.setMaximumSize(QtCore.QSize(100, 150))
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.btn_create = QtGui.QPushButton(self.layoutWidget5)
        self.btn_create.setEnabled(False)
        self.btn_create.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_create.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_create.setDefault(True)
        self.btn_create.setObjectName("btn_create")
        self.horizontalLayout.addWidget(self.btn_create)

        self.retranslateUi(newProjectDialog)
        QtCore.QMetaObject.connectSlotsByName(newProjectDialog)

    def retranslateUi(self, newProjectDialog):
        newProjectDialog.setWindowTitle(QtGui.QApplication.translate("newProjectDialog", "New Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("newProjectDialog", "Create New Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("newProjectDialog", "Select either a symbolic layout (.svg) or netlist (.net or .txt) file.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("newProjectDialog", "Set Up Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("newProjectDialog", "Project Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_openDirectory.setText(QtGui.QApplication.translate("newProjectDialog", "Open Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("newProjectDialog", "Project Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("newProjectDialog", "Select file", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_symbnetfile.setText(QtGui.QApplication.translate("newProjectDialog", "Open File", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_advnetlist.setTitle(QtGui.QApplication.translate("newProjectDialog", "Netlist Details", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("newProjectDialog", "Positive Source  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("newProjectDialog", "Negative Source", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("newProjectDialog", "Enter netlist names for the source leads and output node. Source lead names should correspond to voltage sources defined in the netlist. The output node name should correspond to a net alias or node defined in the netlist.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("newProjectDialog", "Output Node      ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("newProjectDialog", "Netlists will be automatically converted to a symbolic layout.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("newProjectDialog", "Select file type", None, QtGui.QApplication.UnicodeUTF8))
        self.dropdown_filetype.setItemText(0, QtGui.QApplication.translate("newProjectDialog", "File type", None, QtGui.QApplication.UnicodeUTF8))
        self.dropdown_filetype.setItemText(1, QtGui.QApplication.translate("newProjectDialog", "Symbolic layout (.svg)", None, QtGui.QApplication.UnicodeUTF8))
        self.dropdown_filetype.setItemText(2, QtGui.QApplication.translate("newProjectDialog", "Netlist (.net or .txt)", None, QtGui.QApplication.UnicodeUTF8))
        self.dropdown_filetype.setItemText(3, QtGui.QApplication.translate("newProjectDialog", "Layout Script (.psc or .txt)", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancel.setText(QtGui.QApplication.translate("newProjectDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_create.setText(QtGui.QApplication.translate("newProjectDialog", "Create Project", None, QtGui.QApplication.UnicodeUTF8))

