# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'propertiesDeviceDialog.ui'
#
# Created: Tue Sep 27 10:49:31 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_device_propeties(object):
    def setupUi(self, device_propeties):
        device_propeties.setObjectName("device_propeties")
        device_propeties.resize(700, 453)
        self.stackedWidget = QtGui.QStackedWidget(device_propeties)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 10, 321, 211))
        self.stackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setMidLineWidth(-1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.fstm_rect = QtGui.QWidget()
        self.fstm_rect.setObjectName("fstm_rect")
        self.ledt_heat_flow = QtGui.QLineEdit(self.fstm_rect)
        self.ledt_heat_flow.setGeometry(QtCore.QRect(100, 20, 111, 20))
        self.ledt_heat_flow.setObjectName("ledt_heat_flow")
        self.label_9 = QtGui.QLabel(self.fstm_rect)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.fstm_rect)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 81, 20))
        self.label_10.setObjectName("label_10")
        self.ledt_attach_thickness = QtGui.QLineEdit(self.fstm_rect)
        self.ledt_attach_thickness.setGeometry(QtCore.QRect(100, 50, 111, 20))
        self.ledt_attach_thickness.setObjectName("ledt_attach_thickness")
        self.label_21 = QtGui.QLabel(self.fstm_rect)
        self.label_21.setGeometry(QtCore.QRect(220, 20, 91, 20))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtGui.QLabel(self.fstm_rect)
        self.label_22.setGeometry(QtCore.QRect(220, 50, 91, 20))
        self.label_22.setObjectName("label_22")
        self.stackedWidget.addWidget(self.fstm_rect)
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.label = QtGui.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(20, 30, 271, 141))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page)
        self.ssapp = QtGui.QWidget()
        self.ssapp.setObjectName("ssapp")
        self.ledt_attach_thickness_2 = QtGui.QLineEdit(self.ssapp)
        self.ledt_attach_thickness_2.setGeometry(QtCore.QRect(110, 160, 111, 20))
        self.ledt_attach_thickness_2.setObjectName("ledt_attach_thickness_2")
        self.label_12 = QtGui.QLabel(self.ssapp)
        self.label_12.setGeometry(QtCore.QRect(10, 160, 81, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(self.ssapp)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.label_13.setObjectName("label_13")
        self.ledt_avg_current = QtGui.QLineEdit(self.ssapp)
        self.ledt_avg_current.setGeometry(QtCore.QRect(110, 10, 111, 20))
        self.ledt_avg_current.setObjectName("ledt_avg_current")
        self.label_14 = QtGui.QLabel(self.ssapp)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 111, 20))
        self.label_14.setObjectName("label_14")
        self.ledt_vgate = QtGui.QLineEdit(self.ssapp)
        self.ledt_vgate.setGeometry(QtCore.QRect(110, 70, 111, 20))
        self.ledt_vgate.setObjectName("ledt_vgate")
        self.label_15 = QtGui.QLabel(self.ssapp)
        self.label_15.setGeometry(QtCore.QRect(10, 130, 111, 20))
        self.label_15.setObjectName("label_15")
        self.ledt_rds = QtGui.QLineEdit(self.ssapp)
        self.ledt_rds.setGeometry(QtCore.QRect(110, 130, 111, 20))
        self.ledt_rds.setObjectName("ledt_rds")
        self.label_17 = QtGui.QLabel(self.ssapp)
        self.label_17.setGeometry(QtCore.QRect(230, 10, 91, 20))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtGui.QLabel(self.ssapp)
        self.label_18.setGeometry(QtCore.QRect(230, 70, 91, 20))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtGui.QLabel(self.ssapp)
        self.label_19.setGeometry(QtCore.QRect(230, 130, 91, 20))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtGui.QLabel(self.ssapp)
        self.label_20.setGeometry(QtCore.QRect(230, 160, 91, 20))
        self.label_20.setObjectName("label_20")
        self.label_23 = QtGui.QLabel(self.ssapp)
        self.label_23.setGeometry(QtCore.QRect(10, 100, 111, 20))
        self.label_23.setObjectName("label_23")
        self.ledt_vgate_2 = QtGui.QLineEdit(self.ssapp)
        self.ledt_vgate_2.setGeometry(QtCore.QRect(110, 100, 111, 20))
        self.ledt_vgate_2.setObjectName("ledt_vgate_2")
        self.label_24 = QtGui.QLabel(self.ssapp)
        self.label_24.setGeometry(QtCore.QRect(230, 100, 91, 20))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtGui.QLabel(self.ssapp)
        self.label_25.setGeometry(QtCore.QRect(10, 40, 111, 20))
        self.label_25.setObjectName("label_25")
        self.ledt_vdd = QtGui.QLineEdit(self.ssapp)
        self.ledt_vdd.setGeometry(QtCore.QRect(110, 40, 111, 20))
        self.ledt_vdd.setObjectName("ledt_vdd")
        self.label_26 = QtGui.QLabel(self.ssapp)
        self.label_26.setGeometry(QtCore.QRect(230, 40, 91, 20))
        self.label_26.setObjectName("label_26")
        self.stackedWidget.addWidget(self.ssapp)
        self.groupBox_8 = QtGui.QGroupBox(device_propeties)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 240, 671, 121))
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lbl_model_Instruction = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_model_Instruction.setFont(font)
        self.lbl_model_Instruction.setWordWrap(True)
        self.lbl_model_Instruction.setObjectName("lbl_model_Instruction")
        self.gridLayout_7.addWidget(self.lbl_model_Instruction, 0, 0, 1, 1)
        self.label_16 = QtGui.QLabel(device_propeties)
        self.label_16.setGeometry(QtCore.QRect(360, 0, 61, 20))
        self.label_16.setObjectName("label_16")
        self.cmb_device_type = QtGui.QComboBox(device_propeties)
        self.cmb_device_type.setGeometry(QtCore.QRect(400, 0, 271, 18))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_device_type.sizePolicy().hasHeightForWidth())
        self.cmb_device_type.setSizePolicy(sizePolicy)
        self.cmb_device_type.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmb_device_type.setEditable(True)
        self.cmb_device_type.setObjectName("cmb_device_type")
        self.cmb_device_type.addItem("")
        self.cmb_device_type.addItem("")
        self.btn_add = QtGui.QPushButton(device_propeties)
        self.btn_add.setGeometry(QtCore.QRect(360, 380, 321, 23))
        self.btn_add.setObjectName("btn_add")
        self.label_2 = QtGui.QLabel(device_propeties)
        self.label_2.setGeometry(QtCore.QRect(360, 30, 256, 13))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lbl_dev_attach = QtGui.QLabel(device_propeties)
        self.lbl_dev_attach.setGeometry(QtCore.QRect(360, 150, 251, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lbl_dev_attach.setFont(font)
        self.lbl_dev_attach.setObjectName("lbl_dev_attach")
        self.lst_devices_att = QtGui.QListView(device_propeties)
        self.lst_devices_att.setEnabled(True)
        self.lst_devices_att.setGeometry(QtCore.QRect(360, 180, 331, 50))
        self.lst_devices_att.setMaximumSize(QtCore.QSize(16777215, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lst_devices_att.setPalette(palette)
        self.lst_devices_att.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lst_devices_att.setObjectName("lst_devices_att")
        self.lst_devices = QtGui.QListView(device_propeties)
        self.lst_devices.setEnabled(True)
        self.lst_devices.setGeometry(QtCore.QRect(360, 60, 331, 50))
        self.lst_devices.setMaximumSize(QtCore.QSize(16777215, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lst_devices.setPalette(palette)
        self.lst_devices.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lst_devices.setObjectName("lst_devices")
        

        self.retranslateUi(device_propeties)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(device_propeties)

    def retranslateUi(self, device_propeties):
        device_propeties.setWindowTitle(QtGui.QApplication.translate("device_propeties", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("device_propeties", "Heat Flow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("device_propeties", "Attach Thickness", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("device_propeties", "Watt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("device_propeties", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("device_propeties", "Successive Approximation model doesnot support Diode for now", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("device_propeties", "Attach Thickness", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("device_propeties", "Average Current", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("device_propeties", "Gate Drive Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("device_propeties", "Rds", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("device_propeties", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("device_propeties", "V", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("device_propeties", "Ohm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("device_propeties", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("device_propeties", "R Gate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("device_propeties", "Ohm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("device_propeties", "Off state VDD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("device_propeties", "V", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("device_propeties", "Instructions", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_model_Instruction.setText(QtGui.QApplication.translate("device_propeties", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400;\">Welcome to PowerSynth device properties manager. This window will guide you through the process of attaching a device model to your circuit</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("device_propeties", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_device_type.setItemText(0, QtGui.QApplication.translate("device_propeties", "Transistor", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_device_type.setItemText(1, QtGui.QApplication.translate("device_propeties", "Diode", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_device_type.setEditable(False)
        self.btn_add.setText(QtGui.QApplication.translate("device_propeties", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("device_propeties", "Device List:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_dev_attach.setText(QtGui.QApplication.translate("device_propeties", "Select a Device Attach:", None, QtGui.QApplication.UnicodeUTF8))

