# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResponseSurface.ui'
#
# Created: Thu May 18 15:54:07 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ResponseSurface(object):
    def setupUi(self, ResponseSurface):
        ResponseSurface.setObjectName("ResponseSurface")
        ResponseSurface.resize(658, 502)
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(0, 0, 321, 471))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_fmax = QtGui.QLineEdit(self.frame)
        self.lineEdit_fmax.setGeometry(QtCore.QRect(130, 180, 61, 20))
        self.lineEdit_fmax.setObjectName("lineEdit_fmax")
        self.lineEdit_maxL = QtGui.QLineEdit(self.frame)
        self.lineEdit_maxL.setGeometry(QtCore.QRect(160, 110, 61, 20))
        self.lineEdit_maxL.setObjectName("lineEdit_maxL")
        self.lineEdit_minW = QtGui.QLineEdit(self.frame)
        self.lineEdit_minW.setGeometry(QtCore.QRect(60, 60, 61, 20))
        self.lineEdit_minW.setObjectName("lineEdit_minW")
        self.lineEdit_maxW = QtGui.QLineEdit(self.frame)
        self.lineEdit_maxW.setGeometry(QtCore.QRect(160, 60, 61, 20))
        self.lineEdit_maxW.setObjectName("lineEdit_maxW")
        self.lineEdit_minL = QtGui.QLineEdit(self.frame)
        self.lineEdit_minL.setGeometry(QtCore.QRect(60, 110, 61, 20))
        self.lineEdit_minL.setObjectName("lineEdit_minL")
        self.lineEdit_fmin = QtGui.QLineEdit(self.frame)
        self.lineEdit_fmin.setGeometry(QtCore.QRect(30, 180, 61, 20))
        self.lineEdit_fmin.setObjectName("lineEdit_fmin")
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 71, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 41, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(130, 60, 41, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 81, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 110, 41, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(130, 110, 41, 16))
        self.label_9.setObjectName("label_9")
        self.label_14 = QtGui.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(230, 60, 61, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(230, 110, 61, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtGui.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(10, 150, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtGui.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(10, 180, 41, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtGui.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(100, 180, 41, 16))
        self.label_18.setObjectName("label_18")
        self.lineEdit_fstep = QtGui.QLineEdit(self.frame)
        self.lineEdit_fstep.setGeometry(QtCore.QRect(230, 180, 61, 20))
        self.lineEdit_fstep.setObjectName("lineEdit_fstep")
        self.label_19 = QtGui.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(200, 180, 41, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtGui.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(10, 220, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.cmb_DOE = QtGui.QComboBox(self.frame)
        self.cmb_DOE.setGeometry(QtCore.QRect(10, 250, 101, 22))
        self.cmb_DOE.setObjectName("cmb_DOE")
        self.cmb_DOE.addItem("")
        self.cmb_DOE.addItem("")
        self.cmb_DOE.addItem("")
        self.label_21 = QtGui.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(10, 290, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.cmb_mdl = QtGui.QComboBox(self.frame)
        self.cmb_mdl.setGeometry(QtCore.QRect(10, 320, 141, 22))
        self.cmb_mdl.setObjectName("cmb_mdl")
        self.cmb_mdl.addItem("")
        self.cmb_mdl.addItem("")
        self.btn_view = QtGui.QPushButton(self.frame)
        self.btn_view.setGeometry(QtCore.QRect(4, 10, 81, 20))
        self.btn_view.setObjectName("btn_view")
        self.btn_build = QtGui.QPushButton(self.frame)
        self.btn_build.setGeometry(QtCore.QRect(10, 430, 75, 23))
        self.btn_build.setObjectName("btn_build")
        self.label_24 = QtGui.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(10, 360, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.cmb_sims = QtGui.QComboBox(self.frame)
        self.cmb_sims.setGeometry(QtCore.QRect(100, 350, 141, 22))
        self.cmb_sims.setObjectName("cmb_sims")
        self.cmb_sims.addItem("")
        self.cmb_sims.addItem("")
        self.lineEdit_minL_2 = QtGui.QLineEdit(self.frame)
        self.lineEdit_minL_2.setGeometry(QtCore.QRect(90, 400, 161, 20))
        self.lineEdit_minL_2.setObjectName("lineEdit_minL_2")
        self.label_25 = QtGui.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(20, 400, 41, 16))
        self.label_25.setObjectName("label_25")
        self.btn_view_2 = QtGui.QPushButton(self.frame)
        self.btn_view_2.setGeometry(QtCore.QRect(90, 10, 91, 21))
        self.btn_view_2.setObjectName("btn_view_2")
        self.btn_view_3 = QtGui.QPushButton(self.frame)
        self.btn_view_3.setGeometry(QtCore.QRect(190, 10, 91, 21))
        self.btn_view_3.setObjectName("btn_view_3")
        self.listView = QtGui.QListView(self.tab)
        self.listView.setGeometry(QtCore.QRect(330, 30, 311, 171))
        self.listView.setObjectName("listView")
        self.label_22 = QtGui.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(330, 10, 161, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtGui.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(330, 240, 161, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.textEdit = QtGui.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(330, 260, 311, 191))
        self.textEdit.setObjectName("textEdit")
        self.btn_add_layer_stack = QtGui.QPushButton(self.tab)
        self.btn_add_layer_stack.setGeometry(QtCore.QRect(330, 210, 101, 21))
        self.btn_add_layer_stack.setObjectName("btn_add_layer_stack")
        ResponseSurface.addTab(self.tab, "")
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName("tab1")
        ResponseSurface.addTab(self.tab1, "")

        self.retranslateUi(ResponseSurface)
        ResponseSurface.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ResponseSurface)

    def retranslateUi(self, ResponseSurface):
        ResponseSurface.setWindowTitle(QtGui.QApplication.translate("ResponseSurface", "Response Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ResponseSurface", "Trace Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ResponseSurface", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ResponseSurface", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ResponseSurface", "Trace Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ResponseSurface", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ResponseSurface", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("ResponseSurface", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("ResponseSurface", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("ResponseSurface", "Frequency Sweep (kHz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("ResponseSurface", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("ResponseSurface", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("ResponseSurface", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("ResponseSurface", "DOE choice", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_DOE.setItemText(0, QtGui.QApplication.translate("ResponseSurface", "Mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_DOE.setItemText(1, QtGui.QApplication.translate("ResponseSurface", "Piecewise Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_DOE.setItemText(2, QtGui.QApplication.translate("ResponseSurface", "Center Composite", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("ResponseSurface", "Model Type", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_mdl.setItemText(0, QtGui.QApplication.translate("ResponseSurface", "Krigging (recommended)", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_mdl.setItemText(1, QtGui.QApplication.translate("ResponseSurface", "Piecewise Linear (fastest)", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_view.setText(QtGui.QApplication.translate("ResponseSurface", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_build.setText(QtGui.QApplication.translate("ResponseSurface", "Build", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("ResponseSurface", "Simulator", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_sims.setItemText(0, QtGui.QApplication.translate("ResponseSurface", "Q3D", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_sims.setItemText(1, QtGui.QApplication.translate("ResponseSurface", "FastHenry", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("ResponseSurface", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_view_2.setText(QtGui.QApplication.translate("ResponseSurface", "How to", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_view_3.setText(QtGui.QApplication.translate("ResponseSurface", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("ResponseSurface", "Layer Stack Library", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("ResponseSurface", "Model Info:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add_layer_stack.setText(QtGui.QApplication.translate("ResponseSurface", "Add Layer Stack", None, QtGui.QApplication.UnicodeUTF8))
        ResponseSurface.setTabText(ResponseSurface.indexOf(self.tab), QtGui.QApplication.translate("ResponseSurface", " DBC Trace", None, QtGui.QApplication.UnicodeUTF8))
        ResponseSurface.setTabText(ResponseSurface.indexOf(self.tab1), QtGui.QApplication.translate("ResponseSurface", " Corners (TBA)", None, QtGui.QApplication.UnicodeUTF8))

