# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResponseSurface.ui'
#
# Created: Wed May 24 14:44:14 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ResponseSurface(object):
    def setupUi(self, ResponseSurface):
        ResponseSurface.setObjectName("ResponseSurface")
        ResponseSurface.resize(671, 444)
        self.frame = QtGui.QFrame(ResponseSurface)
        self.frame.setGeometry(QtCore.QRect(0, 10, 321, 461))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_20 = QtGui.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(10, 230, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.cmb_DOE = QtGui.QComboBox(self.frame)
        self.cmb_DOE.setGeometry(QtCore.QRect(10, 250, 141, 22))
        self.cmb_DOE.setObjectName("cmb_DOE")
        self.cmb_DOE.addItem("")
        self.cmb_DOE.addItem("")
        self.btn_build = QtGui.QPushButton(self.frame)
        self.btn_build.setGeometry(QtCore.QRect(10, 400, 75, 23))
        self.btn_build.setObjectName("btn_build")
        self.label_24 = QtGui.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(10, 290, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.cmb_sims = QtGui.QComboBox(self.frame)
        self.cmb_sims.setGeometry(QtCore.QRect(110, 290, 141, 22))
        self.cmb_sims.setObjectName("cmb_sims")
        self.cmb_sims.addItem("")
        self.cmb_sims.addItem("")
        self.lineEdit_name = QtGui.QLineEdit(self.frame)
        self.lineEdit_name.setGeometry(QtCore.QRect(70, 340, 161, 20))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_25 = QtGui.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(10, 340, 41, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.btn_add_layer_stack = QtGui.QPushButton(self.frame)
        self.btn_add_layer_stack.setGeometry(QtCore.QRect(10, 0, 111, 21))
        self.btn_add_layer_stack.setObjectName("btn_add_layer_stack")
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 71, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_15 = QtGui.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(260, 140, 61, 16))
        self.label_15.setObjectName("label_15")
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 81, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_18 = QtGui.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(110, 190, 20, 20))
        self.label_18.setObjectName("label_18")
        self.lineEdit_maxL = QtGui.QLineEdit(self.frame)
        self.lineEdit_maxL.setGeometry(QtCore.QRect(180, 140, 61, 20))
        self.lineEdit_maxL.setObjectName("lineEdit_maxL")
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(150, 80, 41, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_minL = QtGui.QLineEdit(self.frame)
        self.lineEdit_minL.setGeometry(QtCore.QRect(40, 140, 61, 20))
        self.lineEdit_minL.setObjectName("lineEdit_minL")
        self.label_19 = QtGui.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(220, 190, 41, 16))
        self.label_19.setObjectName("label_19")
        self.lineEdit_fmax = QtGui.QLineEdit(self.frame)
        self.lineEdit_fmax.setGeometry(QtCore.QRect(140, 190, 61, 20))
        self.lineEdit_fmax.setObjectName("lineEdit_fmax")
        self.lineEdit_fstep = QtGui.QLineEdit(self.frame)
        self.lineEdit_fstep.setGeometry(QtCore.QRect(250, 190, 61, 20))
        self.lineEdit_fstep.setObjectName("lineEdit_fstep")
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(150, 140, 41, 16))
        self.label_9.setObjectName("label_9")
        self.label_16 = QtGui.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(10, 170, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lineEdit_minW = QtGui.QLineEdit(self.frame)
        self.lineEdit_minW.setGeometry(QtCore.QRect(40, 80, 61, 20))
        self.lineEdit_minW.setObjectName("lineEdit_minW")
        self.label_14 = QtGui.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(260, 80, 61, 16))
        self.label_14.setObjectName("label_14")
        self.label_17 = QtGui.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(10, 190, 41, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_maxW = QtGui.QLineEdit(self.frame)
        self.lineEdit_maxW.setGeometry(QtCore.QRect(180, 80, 61, 20))
        self.lineEdit_maxW.setObjectName("lineEdit_maxW")
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 140, 41, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_fmin = QtGui.QLineEdit(self.frame)
        self.lineEdit_fmin.setGeometry(QtCore.QRect(40, 190, 61, 20))
        self.lineEdit_fmin.setObjectName("lineEdit_fmin")
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 41, 16))
        self.label_5.setObjectName("label_5")
        self.label_21 = QtGui.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(110, 140, 41, 16))
        self.label_21.setObjectName("label_21")
        self.label_26 = QtGui.QLabel(self.frame)
        self.label_26.setGeometry(QtCore.QRect(110, 80, 41, 16))
        self.label_26.setObjectName("label_26")
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 111, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.cmb_trace_layer = QtGui.QComboBox(self.frame)
        self.cmb_trace_layer.setGeometry(QtCore.QRect(130, 30, 121, 22))
        self.cmb_trace_layer.setEditable(False)
        self.cmb_trace_layer.setObjectName("cmb_trace_layer")
        self.btn_view_layer_stack = QtGui.QPushButton(self.frame)
        self.btn_view_layer_stack.setEnabled(True)
        self.btn_view_layer_stack.setGeometry(QtCore.QRect(130, 0, 111, 21))
        self.btn_view_layer_stack.setObjectName("btn_view_layer_stack")
        self.label_27 = QtGui.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(240, 340, 61, 16))
        self.label_27.setObjectName("label_27")
        self.list_mdl_lib = QtGui.QListView(ResponseSurface)
        self.list_mdl_lib.setGeometry(QtCore.QRect(320, 30, 341, 171))
        self.list_mdl_lib.setObjectName("list_mdl_lib")
        self.label_22 = QtGui.QLabel(ResponseSurface)
        self.label_22.setGeometry(QtCore.QRect(330, 10, 161, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtGui.QLabel(ResponseSurface)
        self.label_23.setGeometry(QtCore.QRect(330, 210, 161, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.text_edt_model_info = QtGui.QTextEdit(ResponseSurface)
        self.text_edt_model_info.setGeometry(QtCore.QRect(320, 230, 341, 201))
        self.text_edt_model_info.setObjectName("text_edt_model_info")

        self.retranslateUi(ResponseSurface)
        QtCore.QMetaObject.connectSlotsByName(ResponseSurface)

    def retranslateUi(self, ResponseSurface):
        ResponseSurface.setWindowTitle(QtGui.QApplication.translate("ResponseSurface", "ResponseSurface", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("ResponseSurface", "DOE choice", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_DOE.setItemText(0, QtGui.QApplication.translate("ResponseSurface", "Mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_DOE.setItemText(1, QtGui.QApplication.translate("ResponseSurface", "Center Composite", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_build.setText(QtGui.QApplication.translate("ResponseSurface", "Build", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("ResponseSurface", "Simulator", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_sims.setItemText(0, QtGui.QApplication.translate("ResponseSurface", "Q3D", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_sims.setItemText(1, QtGui.QApplication.translate("ResponseSurface", "FastHenry", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("ResponseSurface", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add_layer_stack.setText(QtGui.QApplication.translate("ResponseSurface", "Import Layer Stack", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ResponseSurface", "Trace Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("ResponseSurface", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ResponseSurface", "Trace Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("ResponseSurface", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ResponseSurface", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("ResponseSurface", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ResponseSurface", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("ResponseSurface", "Frequency Sweep (kHz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("ResponseSurface", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("ResponseSurface", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ResponseSurface", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ResponseSurface", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("ResponseSurface", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("ResponseSurface", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("ResponseSurface", "Select Trace Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_view_layer_stack.setText(QtGui.QApplication.translate("ResponseSurface", "View Layer Stack", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("ResponseSurface", ".rsmdl", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("ResponseSurface", "Model Library", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("ResponseSurface", "Model Info:", None, QtGui.QApplication.UnicodeUTF8))

