# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'solutionWindow.ui'
#
# Created: Mon Jun 11 22:33:56 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_layout_form(object):
    def setupUi(self, layout_form):
        layout_form.setObjectName("layout_form")
        layout_form.resize(1056, 904)
        layout_form.setMinimumSize(QtCore.QSize(200, 200))
        self.gridLayout = QtGui.QGridLayout(layout_form)
        self.gridLayout.setObjectName("gridLayout")
        self.tbl_info = QtGui.QTableWidget(layout_form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_info.sizePolicy().hasHeightForWidth())
        self.tbl_info.setSizePolicy(sizePolicy)
        self.tbl_info.setMaximumSize(QtCore.QSize(300, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.tbl_info.setPalette(palette)
        self.tbl_info.setFrameShape(QtGui.QFrame.NoFrame)
        self.tbl_info.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tbl_info.setAlternatingRowColors(True)
        self.tbl_info.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tbl_info.setShowGrid(False)
        self.tbl_info.setWordWrap(True)
        self.tbl_info.setRowCount(0)
        self.tbl_info.setColumnCount(3)
        self.tbl_info.setObjectName("tbl_info")
        self.tbl_info.setColumnCount(3)
        self.tbl_info.setRowCount(0)
        self.tbl_info.horizontalHeader().setVisible(False)
        self.tbl_info.horizontalHeader().setSortIndicatorShown(False)
        self.tbl_info.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tbl_info, 0, 1, 1, 1)
        self.btn_export_selected = QtGui.QPushButton(layout_form)
        self.btn_export_selected.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_export_selected.setObjectName("btn_export_selected")
        self.gridLayout.addWidget(self.btn_export_selected, 6, 1, 1, 1)
        self.line = QtGui.QFrame(layout_form)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 2, 8, 1)
        self.grfx_layout = QtGui.QGraphicsView(layout_form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grfx_layout.sizePolicy().hasHeightForWidth())
        self.grfx_layout.setSizePolicy(sizePolicy)
        self.grfx_layout.setMinimumSize(QtCore.QSize(100, 100))
        self.grfx_layout.setObjectName("grfx_layout")
        self.gridLayout.addWidget(self.grfx_layout, 0, 4, 8, 1)
        self.btn_run_drc = QtGui.QPushButton(layout_form)
        self.btn_run_drc.setObjectName("btn_run_drc")
        self.gridLayout.addWidget(self.btn_run_drc, 3, 1, 1, 1)
        self.cmbox_export_option = QtGui.QComboBox(layout_form)
        self.cmbox_export_option.setObjectName("cmbox_export_option")
        self.cmbox_export_option.addItem("")
        self.cmbox_export_option.addItem("")
        self.cmbox_export_option.addItem("")
        self.cmbox_export_option.addItem("")
        self.cmbox_export_option.addItem("")
        self.cmbox_export_option.addItem("")
        self.cmbox_export_option.addItem("")
        self.cmbox_export_option.setItemText(6, "")
        self.gridLayout.addWidget(self.cmbox_export_option, 5, 1, 1, 1)
        self.label = QtGui.QLabel(layout_form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 1, 1, 1)

        self.retranslateUi(layout_form)
        QtCore.QMetaObject.connectSlotsByName(layout_form)

    def retranslateUi(self, layout_form):
        layout_form.setWindowTitle(QtGui.QApplication.translate("layout_form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_export_selected.setText(QtGui.QApplication.translate("layout_form", "Export Script", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_run_drc.setText(QtGui.QApplication.translate("layout_form", "Run DRC", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbox_export_option.setItemText(0, QtGui.QApplication.translate("layout_form", "Q3D", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbox_export_option.setItemText(1, QtGui.QApplication.translate("layout_form", "Solidworks", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbox_export_option.setItemText(2, QtGui.QApplication.translate("layout_form", "Electrical netlist ", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbox_export_option.setItemText(3, QtGui.QApplication.translate("layout_form", "Thermal netlist", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbox_export_option.setItemText(4, QtGui.QApplication.translate("layout_form", "FastHenry", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbox_export_option.setItemText(5, QtGui.QApplication.translate("layout_form", "EMPro", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("layout_form", "Export options", None, QtGui.QApplication.UnicodeUTF8))

