# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\bxs003\Dropbox\PMLST\code\workspace\PowerCAD\src\powercad\project_builder\ui\newProjectDialog.ui'
#
# Created: Thu Mar 20 14:38:16 2014
#      by: pyside-uic 0.2.14 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_newProjectDialog(object):
    def setupUi(self, newProjectDialog):
        newProjectDialog.setObjectName("newProjectDialog")
        newProjectDialog.resize(555, 205)
        self.gridLayout = QtGui.QGridLayout(newProjectDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(newProjectDialog)
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(newProjectDialog)
        self.label_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(247, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 4)
        self.label = QtGui.QLabel(newProjectDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 4, 1, 1)
        self.txt_name = QtGui.QLineEdit(newProjectDialog)
        self.txt_name.setObjectName("txt_name")
        self.gridLayout.addWidget(self.txt_name, 1, 1, 1, 6)
        self.txt_dir = QtGui.QLineEdit(newProjectDialog)
        self.txt_dir.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txt_dir.setPalette(palette)
        self.txt_dir.setReadOnly(False)
        self.txt_dir.setObjectName("txt_dir")
        self.gridLayout.addWidget(self.txt_dir, 2, 2, 1, 5)
        self.btn_cancel = QtGui.QPushButton(newProjectDialog)
        self.btn_cancel.setMaximumSize(QtCore.QSize(100, 150))
        self.btn_cancel.setObjectName("btn_cancel")
        self.gridLayout.addWidget(self.btn_cancel, 7, 4, 1, 1)
        self.btn_create = QtGui.QPushButton(newProjectDialog)
        self.btn_create.setEnabled(False)
        self.btn_create.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_create.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_create.setDefault(True)
        self.btn_create.setObjectName("btn_create")
        self.gridLayout.addWidget(self.btn_create, 7, 5, 1, 1)
        self.txt_sym_address = QtGui.QLineEdit(newProjectDialog)
        self.txt_sym_address.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txt_sym_address.setPalette(palette)
        self.txt_sym_address.setObjectName("txt_sym_address")
        self.gridLayout.addWidget(self.txt_sym_address, 3, 2, 1, 5)
        self.label_4 = QtGui.QLabel(newProjectDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.btn_openDirectory = QtGui.QToolButton(newProjectDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_openDirectory.sizePolicy().hasHeightForWidth())
        self.btn_openDirectory.setSizePolicy(sizePolicy)
        self.btn_openDirectory.setObjectName("btn_openDirectory")
        self.gridLayout.addWidget(self.btn_openDirectory, 2, 1, 1, 1)
        self.btn_symbLayout = QtGui.QToolButton(newProjectDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_symbLayout.sizePolicy().hasHeightForWidth())
        self.btn_symbLayout.setSizePolicy(sizePolicy)
        self.btn_symbLayout.setObjectName("btn_symbLayout")
        self.gridLayout.addWidget(self.btn_symbLayout, 3, 1, 1, 1)

        self.retranslateUi(newProjectDialog)
        QtCore.QMetaObject.connectSlotsByName(newProjectDialog)

    def retranslateUi(self, newProjectDialog):
        newProjectDialog.setWindowTitle(QtGui.QApplication.translate("newProjectDialog", "New Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("newProjectDialog", "Project Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("newProjectDialog", "Project Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("newProjectDialog", "Create New Project", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancel.setText(QtGui.QApplication.translate("newProjectDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_create.setText(QtGui.QApplication.translate("newProjectDialog", "Create Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("newProjectDialog", "Symbolic Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_openDirectory.setText(QtGui.QApplication.translate("newProjectDialog", "Open Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_symbLayout.setText(QtGui.QApplication.translate("newProjectDialog", "Open File", None, QtGui.QApplication.UnicodeUTF8))

